### ISSUE TITLE
Should Specify Supported Kubernetes Verison

### ISSUE THREAD

**Issue by hi-artem** [sigstore/policy-controller#161]
**Description**

Trying to install Helm release on EKS 1.21 leads to the following error:

```sh
kubernetes version 1.21.14-eks-18ef993 is not compatible, need at least 1.22.0-0
```

Docs should state that this project is only working on Kubernetes 1.22 or newer.

**Comment by vaikas** [comment]
Yes, that comes from Knative. And I'm glad you found out how to work around that. I was curious why the original error message you pasted didn't show the override pointer (maybe you just clipped it?) because it should say you can override it.
Up until very recently we tested with 1.21, it's just that the matrix starts to grow large. Perhaps we could have a cronjob where we test these less frequently (so maybe not on every PR).
As for the API issues, the webhook APIs used are very stable so I wouldn't expect there any goofiness.

**Comment by hi-artem** [comment]
@vaikas Gotcha! You right, I did clip around the line in the output showing the suggestion from Knative.

I think the original intent of this issue is to have a line (or a paragraph) in the docs saying "we only officially support Kubernetes 1.xx"; or maybe just pointing to the matrix of tested versions is enough. 😄

**Comment by hectorj2f** [comment]
@hi-artem We've added in the README a table with all the supported version. https://github.com/sigstore/policy-controller#support-policy

**Comment by cpanato** [comment]
i think we can close this, if this still an issue, please reopen or create a new one
