### ISSUE TITLE
Permissive Webhook Configurations

### ISSUE THREAD

**Issue by johnfosborneiii** [sigstore/policy-controller#208]
I was mucking around the repo and I ended up looking at the webhook configurations [1] and noticed they were permissive but I'm not sure if there's a technical need for them. If not, I'm happy to file a PR. Specifically my questions were around:
1. ValidatingWebhookConfiguration - does not have any rules set [2] so the webhook is registered to receive all events for all resources and resource groups even though its only actually going to do anything for images [3]. Is there a technical reason for that or should I file a PR so that it only registers to receive AdmissionReview objects for manifests with images?
2. I see there's a MutatingWebhookConfiguration, is that needed at all?

[1] https://github.com/sigstore/policy-controller/blob/main/config/500-webhook-configuration.yaml
[2] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#rulewithoperations-v1-admissionregistration-k8s-io
[3] https://github.com/sigstore/policy-controller/blob/main/pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go#L51

**Comment by hectorj2f** [comment]
> ValidatingWebhookConfiguration - does not have any rules set [2] so the webhook is registered to receive all events for all resources and resource groups even though its only actually going to do anything for images [3]. Is there a technical reason for that or should I file a PR so that it only registers to receive AdmissionReview objects for manifests with images?

@johnfosborneiii That validating webhook only watches events from this list of core types https://github.com/sigstore/policy-controller/blob/main/cmd/webhook/main.go#L126. So I feel we could add those types to the webhook configuration as rules.

> I see there's a MutatingWebhookConfiguration, is that needed at all?

Yes, it is used as we are setting some defaulters.

**Comment by vaikas** [comment]
Sorry for the tardy reply here @johnfosborneiii . There's no need to add them in as rules, as they already get added there by the virtue of using Knative webhook machinery. If you fetch the running webhook configurations, you'll see that they get tightened down to exactly only the resources that @hectorj2f pointed to.

The underlying reconcilelogic is here (for the mutating, which is for defaulting as @hectorj2f mentioned):
https://github.com/knative/pkg/blob/main/webhook/resourcesemantics/defaulting/defaulting.go#L170

And for validating:
https://github.com/knative/pkg/blob/main/webhook/resourcesemantics/validation/reconcile_config.go#L138

So there's no need to add those because they get reconciled.

**Comment by johnfosborneiii** [comment]
Very cool, thank you!
