### ISSUE TITLE
Should the controller deny an image if no policy matches  ?

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/policy-controller#235]
**Question**

As a result of a discussion in https://github.com/sigstore/policy-controller/pull/223 and due to the AND'ed nature of the CIPs, we need to understand any potential use cases whenever an image does not match any of the policies. 

The current implementation (added in https://github.com/sigstore/policy-controller/pull/223) admits images not matching any of the list of available policies. However there could be scenarios whenever users might want to deny all the images that don't match any of the policies.

**Comment by vaikas** [comment]
I too think it's useful (as I said in the code review). Haven't heard anybody have any opposing views, so I reckon we should make this an option. I think we probably are going to need a configmap for configuring different TUF roots (don't want them getting mounted, etc.) tracked in #138. So, maybe this is as good of a time as any to add PolicyController configmap so that it can be configured there?
It's a bigger change, so I reckon we get #223 in, then add the configmap support for configuring this deny all behaviour.

**Comment by vaikas** [comment]
What should the default be here in the configmap?
https://github.com/sigstore/policy-controller/pull/270
@DennyHoang 
@elfotografo007 
@hectorj2f 
@tysonkamp (this wouldn't autocomplete for me, so I hope I got it right? 😰 )

Just tagging y'all, since you expressed thumbs up here. Want to get this sorted before the next release. In the #270 the default config in the configmap is allow, but easy enough to change now rather than change after the release.

**Comment by hectorj2f** [comment]
By default, I'd say `deny` if there isn't any matching policy. It is the right way due to security reasons. It is also aligned with the old behaviour, as we were checking the signatures against fulcio by default.

**Comment by tysonkamp** [comment]
I gave the thumbs up above since absent other potentialy nuances here the idea of denying by defatul follows the principle of least privilege. I can think of examples in other domains where this wasn't followed and by the time the vendor made "secure by default" the actual default, they got so much push back from customers because it broke  functionality in their apps that the vendor had to roll it back and "insecure by default" was the final state of things.  The instance I'm referring to opened apps up for HTTP request smuggling :/

**Comment by mattmoor** [comment]
I think aligning with the old behavior is the most user friendly approach here.  Folks still need to label namespaces, so it'd be great to avoid exposing gaps by default.

**Comment by elfotografo007** [comment]
I also support the `deny` default.

**Comment by vaikas** [comment]
I also believe deny by default is the right behaviour 👍 
Just one nit about the old behaviour. It's not exactly the same as with the previous one. With the deny default, if there are no matching policies, it doesn't matter if the image has or has not been signed with Fulcio because no policy matches, then the default (now defaults to deny) will mean that the image will be rejected. I think this is in many ways better because anybody can sign an image with Fulcio so simply checking that the image was signed was not all that useful imho.
If you want that behaviour with the new default, it's easy enough to craft a cip with glob: `**` and static pass. But we should be recommending that :)
